name: Build Application

on:
  push:
    branches-ignore:
      - 'stable'
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - 'flake.lock'
      - '**.nix'
      - 'packages/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.markdownlint**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - 'flake.lock'
      - '**.nix'
      - 'packages/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.markdownlint**'
  workflow_dispatch:

jobs:

  build_debug:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Release
    secrets:
      SPARKLE_ED25519_KEY: ${{ secrets.SPARKLE_ED25519_KEY }}
